// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Todolist struct {
	List      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Complete  sql.NullBool
}
