// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: todoList.sql

package database

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todolist(list, created_at, updated_at)
VALUES($1, $2, $3)
RETURNING list, created_at, updated_at, complete
`

type CreateTodoParams struct {
	List      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todolist, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.List, arg.CreatedAt, arg.UpdatedAt)
	var i Todolist
	err := row.Scan(
		&i.List,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Complete,
	)
	return i, err
}

const getTodoList = `-- name: GetTodoList :many
SELECT list, created_at, updated_at, complete FROM todolist
`

func (q *Queries) GetTodoList(ctx context.Context) ([]Todolist, error) {
	rows, err := q.db.QueryContext(ctx, getTodoList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todolist
	for rows.Next() {
		var i Todolist
		if err := rows.Scan(
			&i.List,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Complete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
